version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: gondola.proxy.rlwy.net:25125
      DB_PORT: 3306
      DB_NAME: railway
      DB_USER: root
      DB_PASSWORD: dkXrjPdzupemWVsfPvQNZLpUifGVqzSU
    volumes:
      - ./:/var/www/html
      - ./my.cnf:/etc/mysql/my.cnf
    restart: unless-stopped
