version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"           # Access app on localhost:8080
    environment:
      DB_HOST: gondola.proxy.rlwy.net:25125           # points to the MySQL container 'db'
      DB_PORT: 3306
      DB_NAME: railway
      DB_USER: root
      DB_PASSWORD: dkXrjPdzupemWVsfPvQNZLpUifGVqzSU
      APP_ENV: production
      APP_DEBUG: "false"
    depends_on:
      - db
    volumes:
      - ./:/var/www/html    # Sync local folder to container
    restart: unless-stopped

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dkXrjPdzupemWVsfPvQNZLpUifGVqzSU
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: dkXrjPdzupemWVsfPvQNZLpUifGVqzSU
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"         # optional: map MySQL port for local access
    restart: unless-stopped

volumes:
  db_data:
